import { randomBytes } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import type { PrivateE2ECommandPort } from "../../domain/private-e2e-command-ports.js";

function esc(value:string):string{return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function basic(header:string|string[]|undefined):{username:string;password:string}|null{if(typeof header!=="string"||!header.startsWith("Basic "))return null;try{const raw=Buffer.from(header.slice(6),"base64").toString("utf8"),i=raw.indexOf(":");return i<0?null:{username:raw.slice(0,i),password:raw.slice(i+1)};}catch{return null;}}
async function form(req:IncomingMessage):Promise<URLSearchParams>{return await new Promise(resolve=>{let body="";req.on("data",chunk=>{body+=chunk.toString();});req.on("end",()=>resolve(new URLSearchParams(body)));});}
function required(params:URLSearchParams,key:string):string{const value=(params.get(key)??"").trim();if(!value)throw new Error(`${key} is required`);return value;}
function checked(params:URLSearchParams,key:string):boolean{return params.get(key)==="on";}

export interface PrivateE2EHttpOptions {password:string;username?:string;host?:string;port?:number;now?:()=>string;controlCenterBaseUrl?:string;allowedAccountsConfigured:boolean;}
export class PrivateE2EHttpServer {
  private server:Server|undefined;private readonly csrf=randomBytes(24).toString("hex");private readonly now:()=>string;
  constructor(private readonly commands:PrivateE2ECommandPort,private readonly options:PrivateE2EHttpOptions){if(!options.password)throw new Error("Private E2E UI password is required");this.now=options.now??(()=>new Date().toISOString());}
  private authorized(req:IncomingMessage):boolean{const auth=basic(req.headers.authorization);return Boolean(auth&&auth.username===(this.options.username??"flerdvision")&&auth.password===this.options.password);}
  private deny(res:ServerResponse):void{res.statusCode=401;res.setHeader("WWW-Authenticate",'Basic realm="Flerdvision Private E2E"');res.end("Authentication required");}
  private redirect(res:ServerResponse):void{res.statusCode=303;res.setHeader("Location","/");res.end();}
  private hidden(runId:string):string{return`<input type=hidden name=csrf value="${this.csrf}"><input type=hidden name=runId value="${esc(runId)}">`;}
  private page():string{
    const control=(this.options.controlCenterBaseUrl??"http://127.0.0.1:8790").replace(/\/$/,""),candidates=this.commands.candidates(),runs=this.commands.runs();
    const candidateRows=candidates.map(item=>`<tr><td><code>${esc(item.intent.intentId)}</code></td><td>${esc(item.intent.platform)} · <code>${esc(item.intent.accountId)}</code></td><td><code>${esc(item.routeId)}</code></td><td>${item.surfaceContractId?`<code>${esc(item.surfaceContractId)}</code>`:'<span class=bad>MISSING</span>'}</td><td><form method=post action=/start><input type=hidden name=csrf value="${this.csrf}"><input type=hidden name=intentId value="${esc(item.intent.intentId)}"><input name=note placeholder="Test note"><button>Private E2E starten</button></form></td></tr>`).join("");
    const runCards=runs.map(view=>{const run=view.run,state=view.intentState??"current state shown after refresh",gates=[...view.gates].sort((a,b)=>a.checkedAt.localeCompare(b.checkedAt));const gateRows=gates.map(g=>`<tr><td>${esc(g.gate)}</td><td class="${g.status==="PASS"?"ok":g.status==="FAIL"?"bad":"warn"}">${esc(g.status)}</td><td>${esc(g.summary)}</td><td>${esc(new Date(g.checkedAt).toLocaleString("de-AT",{timeZone:"Europe/Vienna"}))}</td></tr>`).join("");const intent=view.intent;
      return`<article class=card><h2>${esc(run.status)} · ${esc(run.platform)} · <code>${esc(run.accountId)}</code></h2><p>Run <code>${esc(run.runId)}</code>${intent?` · Intent <code>${esc(intent.intentId)}</code>`:""} · ${esc(state)}</p><p>Route ${view.routeId?`<code>${esc(view.routeId)}</code>`:"—"} · Surface ${view.surfaceContractId?`<code>${esc(view.surfaceContractId)}</code>`:"—"}</p><div class=actions>
      <form method=post action=/sync>${this.hidden(run.runId)}<button>Technische Evidence synchronisieren</button></form>
      <details><summary>Zero-viewer Privacy attestieren</summary><form method=post action=/privacy>${this.hidden(run.runId)}<label><input type=checkbox name=accountPrivate required> Account private</label><input type=number min=0 name=approvedFollowers value=0 required><label><input type=checkbox name=contactsSyncOff required> Contacts sync off</label><label><input type=checkbox name=crossPostingOff required> Cross-posting off</label><label><input type=checkbox name=testMediaOnly checked required> Test media only</label><button>Privacy attestieren</button></form></details>
      <form method=post action=/prepare>${this.hidden(run.runId)}<button>Retained PREPARE_ONLY bis Final Boundary</button></form>
      <form method=post action=/cancel>${this.hidden(run.runId)}<button>Prepared Session abbrechen</button></form>
      <form method=post action=/final class=danger>${this.hidden(run.runId)}<input name=confirm placeholder="PRIVATE_E2E_FINAL_ACTION" required><button>ONE-SHOT Final Action</button></form>
      <form method=post action=/verify>${this.hidden(run.runId)}<button>Verification jetzt ausführen</button></form>
      <form method=post action=/cleanup>${this.hidden(run.runId)}<input name=confirm placeholder="PRIVATE_E2E_TEST_POST_DELETED" required><input name=note placeholder="Wie/wo gelöscht + Evidence" required><button>Cleanup bestätigen</button></form></div>
      <table><tr><th>Gate</th><th>Status</th><th>Summary</th><th>Zeit</th></tr>${gateRows||'<tr><td colspan=4>Noch keine Gates.</td></tr>'}</table></article>`;}).join("");
    const warning=this.options.allowedAccountsConfigured?"":'<div class="card bad"><strong>Private E2E ist sicher leer:</strong> `FLERDVISION_PRIVATE_E2E_ACCOUNT_IDS` ist nicht gesetzt. Es werden keine Kandidaten angeboten.</div>';
    return`<!doctype html><html lang=de><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Flerdvision Private E2E</title><style>body{font-family:system-ui,-apple-system,sans-serif;background:#f5f7f6;color:#18221f;max-width:1450px;margin:auto;padding:28px}.card{background:#fff;border:1px solid #dfe5e2;border-radius:12px;padding:18px;margin:14px 0}.ok{color:#21704a}.warn{color:#8a6516}.bad{color:#aa392f}.actions form,.actions details{display:inline-block;margin:5px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:8px;border-bottom:1px solid #e7ecea;vertical-align:top}button,input{font:inherit;padding:7px;border:1px solid #bec8c5;border-radius:6px}.danger{border:1px solid #aa392f;padding:6px;border-radius:8px}code{background:#edf1ef;padding:2px 4px;border-radius:4px}</style></head><body><p><a href="${esc(control)}/test-lab">← Product Control Center</a></p><h1>Private E2E</h1><p>Nur explizit allowlistete private Test-Accounts. Technische Gates werden aus realer Evidence abgeleitet. Der Final-Action-Token wird serverintern one-shot erzeugt und nie angezeigt.</p>${warning}<div class=card><h2>SCHEDULED Test-Intents</h2><table><tr><th>Intent</th><th>Account</th><th>Route</th><th>Surface</th><th></th></tr>${candidateRows||'<tr><td colspan=5>Keine erlaubten SCHEDULED Test-Intents.</td></tr>'}</table></div>${runCards||'<div class=card>Noch kein Private-E2E-Run.</div>'}</body></html>`;
  }
  private async handle(req:IncomingMessage,res:ServerResponse):Promise<void>{if(!this.authorized(req)){this.deny(res);return;}const path=new URL(req.url??"/","http://127.0.0.1").pathname,method=req.method??"GET";try{if(method==="GET"&&path==="/"){res.statusCode=200;res.setHeader("Content-Type","text/html; charset=utf-8");res.end(this.page());return;}if(method!=="POST"){res.statusCode=404;res.end("Not found");return;}const params=await form(req);if(params.get("csrf")!==this.csrf){res.statusCode=403;res.end("Invalid CSRF token");return;}if(path==="/start")this.commands.start(required(params,"intentId"),params.get("note")??undefined,this.now());else{const runId=required(params,"runId");if(path==="/sync")await this.commands.syncEvidence(runId,this.now());else if(path==="/privacy")this.commands.attestPrivacy(runId,{accountPrivate:checked(params,"accountPrivate"),approvedFollowers:Number(required(params,"approvedFollowers")),contactsSyncOff:checked(params,"contactsSyncOff"),crossPostingOff:checked(params,"crossPostingOff"),testMediaOnly:checked(params,"testMediaOnly")},this.now());else if(path==="/prepare")await this.commands.prepare(runId,this.now());else if(path==="/cancel")await this.commands.cancelPrepared(runId,this.now());else if(path==="/final")await this.commands.invokeFinal(runId,required(params,"confirm"),this.now());else if(path==="/verify")await this.commands.verify(runId,this.now());else if(path==="/cleanup")this.commands.confirmCleanup(runId,required(params,"confirm"),required(params,"note"),this.now());else{res.statusCode=404;res.end("Not found");return;}}this.redirect(res);}catch(error){res.statusCode=409;res.setHeader("Content-Type","text/plain; charset=utf-8");res.end(error instanceof Error?error.message:String(error));}}
  async start():Promise<{host:string;port:number}>{if(this.server)throw new Error("Private E2E UI already started");const host=this.options.host??"127.0.0.1",port=this.options.port??0;this.server=createServer((req,res)=>{void this.handle(req,res);});await new Promise<void>(resolve=>this.server!.listen(port,host,resolve));const address=this.server.address();if(!address||typeof address==="string")throw new Error("Private E2E UI did not expose TCP address");return{host,port:address.port};}
  async stop():Promise<void>{if(!this.server)return;const server=this.server;this.server=undefined;await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
}
