import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DatabaseSync } from "node:sqlite";
import { DEFAULT_SCHEDULING_POLICY } from "../dist/domain/scheduling.js";
import { SqliteDistributionProvenanceStore, DistributionProvenanceConflictError } from "../dist/adapters/distribution/sqlite-provenance.js";
import { DistributionPlanProvenanceService, DistributionIntentMaterializer } from "../dist/application/distribution-intent-materializer.js";
import { DistributionPostingContextResolver, DistributionIntentContextError } from "../dist/application/posting-context-resolver.js";

function setup() {
  const profile = { postingProfileId:"tt-only", displayName:"TikTok Only You", platform:"tiktok", format:"tiktok", visibility:"only_you", commentsEnabled:true, duetEnabled:false, stitchEnabled:false, enabled:true };
  let current = { revision:1, updatedAt:"2026-08-27T06:00:00.000Z", config:{ sources:[{ connectionId:"src",displayName:"Drive",kind:"local_folder",rootRef:"mount",enabled:true,disposition:{mode:"database_only",leavePartialUntouched:true,leaveBlockedUntouched:true}}], lanes:[{laneId:"lane",connectionId:"src",displayName:"Lane",folderRef:"f",folderPath:"Creator / Mittwoch",interpretation:{kind:"flat"},enabled:true}], postingProfiles:[profile], copyProfiles:[{copyProfileId:"copy",displayName:"Copy",versionId:"v1",strategy:"template",enabled:true}], routes:[{routeId:"r1",displayName:"Creator TikTok",laneId:"lane",accountId:"tt1",platform:"tiktok",postingProfileId:"tt-only",copyProfileId:"copy",schedulePolicyId:"default",requirement:"REQUIRED",enabled:true}], activationCursors:[{laneId:"lane",mode:"NEW_ONLY",activatedAt:"2026-08-27T05:00:00.000Z"}] }, schedulePolicies:{default:DEFAULT_SCHEDULING_POLICY}, planningPolicy:{contentOrder:"FILENAME_NUMERIC_PREFIX",lateArrival:"NEXT_AVAILABLE_SLOT",overflow:"BACKLOG_NEXT_DAY"} };
  const config = { load(){ return current; }, save(){ throw new Error("not used"); } };
  const delivery = { deliveryId:"d1",routeId:"r1",assetId:"a1",contentId:"c1",creatorId:"creator",laneId:"lane",accountId:"tt1",platform:"tiktok",format:"tiktok",postingProfileId:"tt-only",copyProfileId:"copy",copyVersionId:"v1",requirement:"REQUIRED",businessDate:"2026-08-27",slotKey:"slot-1",scheduledFor:"2026-08-27T07:00:00.000Z",windowStartAt:"2026-08-27T06:30:00.000Z",windowEndAt:"2026-08-27T07:30:00.000Z" };
  const plan = { planId:"plan1",businessDate:"2026-08-27",generatedAt:"2026-08-27T06:00:00.000Z",deliveries:[delivery],gaps:[],backlog:[] };
  return { profile, config, delivery, plan, get current(){return current;}, setCurrent(value){current=value;} };
}
class FakeControl { intents=new Map(); reservations=new Map(); createOrGetIntent(intent,now){const existing=this.intents.get(intent.intentId);if(existing)return{created:false,record:existing};const record={intent,state:"PLANNED",createdAt:now,updatedAt:now};this.intents.set(intent.intentId,record);return{created:true,record};} getIntent(id){return this.intents.get(id)??null;} listIntents(){return[...this.intents.values()];} transitionIntent(id,to,now){const r=this.intents.get(id);const n={...r,state:to,updatedAt:now};this.intents.set(id,n);return n;} reserveIntent(id,reservation,now){const r=this.intents.get(id);if(!r||r.state!=="READY")throw new Error("not READY");this.reservations.set(id,reservation);this.transitionIntent(id,"SCHEDULED",now);return reservation;} getReservationForIntent(id){return this.reservations.get(id)??null;} listReservations(){return[...this.reservations.values()];} listDueReservations(){return[]} listMissedReservations(){return[]} }
function provenanceStore(){const root=mkdtempSync(join(tmpdir(),"flerdvision-prov-"));const path=join(root,"db.sqlite");return{path,store:new SqliteDistributionProvenanceStore(path)}}

test("plan provenance freezes route/source/profile/schedule semantics and is idempotent",()=>{const f=setup(),p=provenanceStore(),service=new DistributionPlanProvenanceService(f.config,p.store);const first=service.capture(f.plan,"2026-08-27T06:01:00Z"),second=service.capture(f.plan,"2026-08-27T06:02:00Z");assert.equal(first.created,true);assert.equal(second.created,false);assert.equal(first.record.provenance.routeSnapshots.r1.postingProfile.visibility,"only_you");p.store.close();});
test("materializer persists provenance before a scheduled core intent and is idempotent",()=>{const f=setup(),p=provenanceStore(),control=new FakeControl();new DistributionPlanProvenanceService(f.config,p.store).capture(f.plan,"2026-08-27T06:01:00Z");const svc=new DistributionIntentMaterializer(control,f.config,p.store);const first=svc.ensureIntents(f.plan,"2026-08-27T06:02:00Z");assert.deepEqual([first.created,first.existing,first.blocked],[1,0,0]);const record=[...control.intents.values()][0];assert.equal(record.state,"SCHEDULED");assert.equal(p.store.getIntent(record.intent.intentId).envelope.provenance.postingProfileSnapshot.visibility,"only_you");const second=svc.ensureIntents(f.plan,"2026-08-27T06:03:00Z");assert.deepEqual([second.created,second.existing,second.blocked],[0,1,0]);p.store.close();});
test("config change after plan capture blocks materialization before executable intent exists",()=>{const f=setup(),p=provenanceStore(),control=new FakeControl();new DistributionPlanProvenanceService(f.config,p.store).capture(f.plan,"2026-08-27T06:01:00Z");f.setCurrent({...f.current,revision:2,config:{...f.current.config,postingProfiles:[{...f.profile,visibility:"everyone"}]}});const report=new DistributionIntentMaterializer(control,f.config,p.store).ensureIntents(f.plan,"2026-08-27T06:02:00Z");assert.equal(report.blocked,1);assert.equal(control.intents.size,0);assert.match(report.issues[0].reason,/changed after DailyPlan/);p.store.close();});
test("posting resolver returns frozen profile only while route snapshot is current",()=>{const f=setup(),p=provenanceStore(),control=new FakeControl();new DistributionPlanProvenanceService(f.config,p.store).capture(f.plan,"2026-08-27T06:01:00Z");new DistributionIntentMaterializer(control,f.config,p.store).ensureIntents(f.plan,"2026-08-27T06:02:00Z");const intent=[...control.intents.values()][0].intent,resolver=new DistributionPostingContextResolver(p.store,f.config);assert.equal(resolver.resolve(intent).postingProfile.visibility,"only_you");f.setCurrent({...f.current,revision:2,config:{...f.current.config,postingProfiles:[{...f.profile,visibility:"everyone"}]}});assert.throws(()=>resolver.resolve(intent),DistributionIntentContextError);p.store.close();});
test("same intent cannot be remapped to different provenance",()=>{const f=setup(),p=provenanceStore(),control=new FakeControl();new DistributionPlanProvenanceService(f.config,p.store).capture(f.plan,"2026-08-27T06:01:00Z");new DistributionIntentMaterializer(control,f.config,p.store).ensureIntents(f.plan,"2026-08-27T06:02:00Z");const existing=p.store.getIntentByDelivery("d1").envelope;assert.throws(()=>p.store.putIntent({...existing,provenance:{...existing.provenance,routeId:"other"}},"2026-08-27T06:03:00Z"),DistributionProvenanceConflictError);p.store.close();});
test("provenance tables are append-only at SQLite level",()=>{const f=setup(),p=provenanceStore();new DistributionPlanProvenanceService(f.config,p.store).capture(f.plan,"2026-08-27T06:01:00Z");p.store.close();const db=new DatabaseSync(p.path);assert.throws(()=>db.prepare("UPDATE distribution_plan_provenance SET created_at=? WHERE plan_id=?").run("x","plan1"),/append-only/);db.close();});
