import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { ChromiumCdpRuntimeAdapter } from "../dist/adapters/browser/chromium-cdp.js";
import { BrowserCalibrationRecorder } from "../dist/adapters/browser/calibration-recorder.js";
import { buildRecordedSurfaceContract, qualifySurfaceContract } from "../dist/application/platform-surface-contract.js";
import { surfaceRecipeForPostingProfile } from "../dist/domain/platform-surface.js";

function identity(){return{identityId:"browser:test",accountId:"acct:test",platform:"instagram",profileKey:"instagram/test",expectedHandle:"test",enabled:true};}
async function page(){const root=mkdtempSync(join(tmpdir(),"flerdvision-cal-")),profiles=join(root,"profiles");mkdirSync(profiles,{recursive:true});const runtime=new ChromiumCdpRuntimeAdapter({profilesRoot:profiles});const p=await runtime.launch(identity(),{headless:true,initialUrl:"about:blank"});await p.evaluate(`(() => { document.body.innerHTML='<button id="normal" data-testid="create" aria-label="Create">Create</button><button id="final" data-testid="share" aria-label="Share">Share</button>'; document.querySelector('#normal').addEventListener('click',e=>{e.currentTarget.dataset.clicked='yes'}); document.querySelector('#final').addEventListener('click',e=>{e.currentTarget.dataset.clicked='yes'}); return true; })()`);return p;}

test("calibration recorder observes reversible click with semantic locator candidates",async()=>{const p=await page(),recorder=new BrowserCalibrationRecorder();try{await recorder.arm(p,"OPEN_CREATE","OBSERVE_ACTION");await p.evaluate(`document.querySelector('#normal').click()`);const obs=await recorder.readObservation(p,{accountId:"acct:test",platform:"instagram",format:"reel",stepKey:"OPEN_CREATE",observedAt:"2026-08-27T08:00:00Z"});assert.equal(obs.actionBlocked,false);assert.ok(obs.candidates.some(c=>c.locator.kind==="role"&&c.locator.role==="button"&&c.locator.value==="Create"));assert.equal(await p.evaluate(`document.querySelector('#normal').dataset.clicked`),"yes");}finally{await p.close();}});
test("final-action calibration records target but prevents final button handler",async()=>{const p=await page(),recorder=new BrowserCalibrationRecorder();try{await recorder.arm(p,"FINAL_ACTION","BLOCK_ACTION");await p.evaluate(`document.querySelector('#final').click()`);const obs=await recorder.readObservation(p,{accountId:"acct:test",platform:"instagram",format:"reel",stepKey:"FINAL_ACTION",observedAt:"2026-08-27T08:00:00Z"});assert.equal(obs.actionBlocked,true);assert.ok(obs.candidates.some(c=>c.locator.kind==="role"&&c.locator.value==="Share"));assert.equal(await p.evaluate(`document.querySelector('#final').dataset.clicked || null`),null);}finally{await p.close();}});
function env(){return{browserFamily:"chromium",browserMajor:144,language:"en-US",timeZone:"Europe/Vienna",viewportWidth:1280,viewportHeight:720,deviceScaleFactor:1,fingerprint:"env"};}
function observation(stepKey,mode="OBSERVE_ACTION"){return{observationId:`o:${stepKey}`,accountId:"acct",platform:"tiktok",format:"tiktok",stepKey,observedAt:"2026-08-27T08:00:00Z",environment:env(),currentUrl:"https://www.tiktok.com/",tagName:"button",candidates:[{locator:{kind:"role",role:"button",value:stepKey,exact:true},confidence:"HIGH",reason:"test"}],actionBlocked:mode==="BLOCK_ACTION"};}
test("TikTok recipe includes visibility/comments/duet/stitch and blocked final boundary",()=>{const profile={postingProfileId:"tt",displayName:"TikTok Public",platform:"tiktok",format:"tiktok",visibility:"everyone",commentsEnabled:true,duetEnabled:true,stitchEnabled:true,enabled:true};const recipe=surfaceRecipeForPostingProfile(profile);assert.ok(["VISIBILITY","COMMENTS","DUET","STITCH"].every(key=>recipe.steps.some(s=>s.stepKey===key)));assert.equal(recipe.steps.find(s=>s.stepKey==="FINAL_ACTION").actionMode,"BLOCK_ACTION");});
test("Trial Reel recipe explicitly includes trial-mode selection",()=>{const profile={postingProfileId:"trial",displayName:"Trial",platform:"instagram",format:"trial_reel",commentsEnabled:true,shareToFeed:false,crosspostFacebook:false,enabled:true};assert.ok(surfaceRecipeForPostingProfile(profile).steps.some(s=>s.stepKey==="TRIAL_MODE"));});
test("recorded contract chooses locator stable across observations and stays RECORDED",()=>{const profile={postingProfileId:"tt",displayName:"TikTok Public",platform:"tiktok",format:"tiktok",visibility:"everyone",commentsEnabled:true,duetEnabled:true,stitchEnabled:true,enabled:true};const recipe=surfaceRecipeForPostingProfile(profile);const observations=recipe.steps.flatMap(s=>[observation(s.stepKey,s.actionMode),{...observation(s.stepKey,s.actionMode),observationId:`o2:${s.stepKey}`,observedAt:"2026-08-27T08:01:00Z"}]);const contract=buildRecordedSurfaceContract({accountId:"acct",profile,observations,createdAt:"2026-08-27T08:02:00Z"});assert.equal(contract.status,"RECORDED");assert.equal(contract.steps.length,recipe.steps.length);});
test("contract becomes CALIBRATED only after latest three prepare-only replays pass without final action",()=>{const profile={postingProfileId:"tt",displayName:"TikTok",platform:"tiktok",format:"tiktok",visibility:"only_you",commentsEnabled:true,duetEnabled:false,stitchEnabled:false,enabled:true};const recipe=surfaceRecipeForPostingProfile(profile),observations=recipe.steps.map(s=>observation(s.stepKey,s.actionMode));const contract=buildRecordedSurfaceContract({accountId:"acct",profile,observations,createdAt:"2026-08-27T08:00:00Z"});const e=(n,passed=true,final=false)=>({replayId:`r${n}`,contractId:contract.contractId,checkedAt:`2026-08-27T08:0${n}:00Z`,passed,reachedFinalActionBoundary:passed,finalActionInvoked:final,environmentFingerprint:"env",artifactRefs:[]});assert.throws(()=>qualifySurfaceContract(contract,[e(1),e(2)],"2026-08-27T08:10:00Z"),/three successful/);assert.equal(qualifySurfaceContract(contract,[e(1),e(2),e(3)],"2026-08-27T08:10:00Z").status,"CALIBRATED");assert.throws(()=>qualifySurfaceContract(contract,[e(1),e(2),e(3,true,true)],"2026-08-27T08:10:00Z"),/never invoke final/);});
