import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DatabaseSync } from "node:sqlite";
import { SqlitePlatformSurfaceStore } from "../dist/adapters/distribution/sqlite-surface-store.js";
import { PlatformSurfaceRegistryService } from "../dist/application/platform-surface-registry.js";
import { buildCalibrationReplayPlan, buildPlatformExecutionPlan } from "../dist/application/platform-execution-plan.js";
import { surfaceRecipeForPostingProfile } from "../dist/domain/platform-surface.js";

const environment={browserFamily:"chromium",browserMajor:144,language:"en-US",timeZone:"Europe/Vienna",viewportWidth:1280,viewportHeight:720,deviceScaleFactor:1,fingerprint:"env"};
function observation(accountId,platform,format,step,mode){return{observationId:`${accountId}:${format}:${step}`,accountId,platform,format,stepKey:step,observedAt:"2026-08-27T08:00:00Z",environment,currentUrl:"about:blank",tagName:"button",candidates:[{locator:{kind:"role",role:"button",value:step,exact:true},confidence:"HIGH",reason:"fixture"}],actionBlocked:mode==="BLOCK_ACTION"};}
function store(){const root=mkdtempSync(join(tmpdir(),"surface-store-")),path=join(root,"db.sqlite");return{path,value:new SqlitePlatformSurfaceStore(path)};}
function recordRecipe(registry,accountId,profile){for(const step of surfaceRecipeForPostingProfile(profile).steps)registry.recordObservation(observation(accountId,profile.platform,profile.format,step.stepKey,step.actionMode));}
function contextFor(profile){const intent={intentId:"i",contentId:"c",creatorId:"creator",platform:profile.platform,accountId:"acct",format:profile.format,copyVersionId:"v1",scheduledFor:"2026-08-27T09:00:00Z",idempotencyKey:"k"};const provenance={planId:"p",deliveryId:"d",routeId:"r",laneId:"l",assetId:"a",postingProfileId:profile.postingProfileId,copyProfileId:"copy",schedulePolicyId:"default",routeSnapshotFingerprint:"fp",postingProfileSnapshot:profile};return{intent,provenance,postingProfile:profile};}

test("surface registry stores observations/contracts/replays append-only and promotes by new contract version",()=>{const db=store(),registry=new PlatformSurfaceRegistryService(db.value),profile={postingProfileId:"tt",displayName:"TT Only",platform:"tiktok",format:"tiktok",visibility:"only_you",commentsEnabled:true,duetEnabled:false,stitchEnabled:false,enabled:true};recordRecipe(registry,"acct",profile);const recorded=registry.buildRecorded("acct",profile,"2026-08-27T08:01:00Z");assert.equal(recorded.contract.status,"RECORDED");for(let n=1;n<=3;n++)registry.recordReplay({replayId:`r${n}`,contractId:recorded.contract.contractId,checkedAt:`2026-08-27T08:0${n+1}:00Z`,passed:true,reachedFinalActionBoundary:true,finalActionInvoked:false,environmentFingerprint:"env",artifactRefs:[]});const qualified=registry.qualify("acct",profile,"2026-08-27T08:10:00Z");assert.equal(qualified.contract.status,"CALIBRATED");assert.notEqual(qualified.versionId,recorded.versionId);db.value.close();const raw=new DatabaseSync(db.path);assert.throws(()=>raw.prepare("DELETE FROM platform_surface_contract_versions").run(),/append-only/);raw.close();});
test("execution plan turns frozen TikTok values into explicit UI settings and ends at boundary",()=>{const db=store(),registry=new PlatformSurfaceRegistryService(db.value),profile={postingProfileId:"tt",displayName:"TT Only",platform:"tiktok",format:"tiktok",visibility:"only_you",commentsEnabled:true,duetEnabled:false,stitchEnabled:false,enabled:true};recordRecipe(registry,"acct",profile);const recorded=registry.buildRecorded("acct",profile,"2026-08-27T08:01:00Z");for(let n=1;n<=3;n++)registry.recordReplay({replayId:`r${n}`,contractId:recorded.contract.contractId,checkedAt:`2026-08-27T08:0${n+1}:00Z`,passed:true,reachedFinalActionBoundary:true,finalActionInvoked:false,environmentFingerprint:"env",artifactRefs:[]});const contract=registry.qualify("acct",profile,"2026-08-27T08:10:00Z").contract;const plan=buildPlatformExecutionPlan(contextFor(profile),contract);assert.equal(plan.actions.find(a=>a.stepKey==="VISIBILITY").expectedValue,"only_you");assert.equal(plan.actions.find(a=>a.stepKey==="DUET").expectedValue,false);assert.equal(plan.actions.at(-1).operation,"FINAL_BOUNDARY");db.value.close();});
test("recorded surface contract is calibration-replay only",()=>{const profile={postingProfileId:"tt",displayName:"TT",platform:"tiktok",format:"tiktok",visibility:"everyone",commentsEnabled:true,duetEnabled:true,stitchEnabled:true,enabled:true};const steps=surfaceRecipeForPostingProfile(profile).steps.map(s=>({stepKey:s.stepKey,label:s.label,actionMode:s.actionMode,locator:{kind:"text",value:s.stepKey},fallbackLocators:[],observations:1}));const contract={contractId:"c",accountId:"acct",platform:"tiktok",format:"tiktok",postingProfileId:"tt",environment,steps,status:"RECORDED",createdAt:"2026-08-27T08:00:00Z"};const context=contextFor(profile);assert.throws(()=>buildPlatformExecutionPlan(context,contract),/not calibrated/);const replay=buildCalibrationReplayPlan(context,contract);assert.equal(replay.surfaceContractId,"c");assert.equal(replay.actions.at(-1).operation,"FINAL_BOUNDARY");assert.equal(replay.actions.filter(a=>a.operation==="FINAL_BOUNDARY").length,1);});
test("Instagram Trial execution plan drives trial/share/feed values",()=>{const profile={postingProfileId:"trial",displayName:"Trial",platform:"instagram",format:"trial_reel",commentsEnabled:false,shareToFeed:false,crosspostFacebook:false,enabled:true};const steps=surfaceRecipeForPostingProfile(profile).steps.map(s=>({stepKey:s.stepKey,label:s.label,actionMode:s.actionMode,locator:{kind:"text",value:s.stepKey},fallbackLocators:[],observations:1}));const contract={contractId:"c",accountId:"acct",platform:"instagram",format:"trial_reel",postingProfileId:"trial",environment,steps,status:"CALIBRATED",createdAt:"2026-08-27T08:00:00Z",calibratedAt:"2026-08-27T08:10:00Z"};const plan=buildPlatformExecutionPlan(contextFor(profile),contract);assert.equal(plan.actions.find(a=>a.stepKey==="TRIAL_MODE").expectedValue,true);assert.equal(plan.actions.find(a=>a.stepKey==="SHARE_TO_FEED").expectedValue,false);assert.equal(plan.actions.find(a=>a.stepKey==="COMMENTS").expectedValue,false);});
