import { createHash } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import type { Platform, PublicationFormat } from "../../domain/model.js";
import type { PlatformSurfaceStorePort, StoredSurfaceContractVersion } from "../../domain/platform-surface-ports.js";
import type { PlatformSurfaceContract, SurfaceReplayEvidence, SurfaceStepObservation } from "../../domain/platform-surface.js";

function hash(value:string):string{return createHash("sha256").update(value).digest("hex");}
function iso(value:string):string{const d=new Date(value);if(Number.isNaN(d.getTime()))throw new Error(`Invalid timestamp: ${value}`);return d.toISOString();}
export class PlatformSurfaceStoreConflict extends Error {}

export class SqlitePlatformSurfaceStore implements PlatformSurfaceStorePort {
  private readonly db:DatabaseSync;
  constructor(databasePath:string){this.db=new DatabaseSync(databasePath);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;");this.db.exec(`CREATE TABLE IF NOT EXISTS platform_surface_observations(observation_id TEXT PRIMARY KEY,account_id TEXT NOT NULL,platform TEXT NOT NULL,format TEXT NOT NULL,step_key TEXT NOT NULL,observation_json TEXT NOT NULL,payload_hash TEXT NOT NULL,observed_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS platform_surface_contract_versions(version_id TEXT PRIMARY KEY,contract_id TEXT NOT NULL,account_id TEXT NOT NULL,posting_profile_id TEXT NOT NULL,status TEXT NOT NULL,contract_json TEXT NOT NULL,payload_hash TEXT NOT NULL,recorded_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS platform_surface_contract_lookup ON platform_surface_contract_versions(account_id,posting_profile_id,recorded_at);CREATE TABLE IF NOT EXISTS platform_surface_replays(replay_id TEXT PRIMARY KEY,contract_id TEXT NOT NULL,evidence_json TEXT NOT NULL,payload_hash TEXT NOT NULL,checked_at TEXT NOT NULL);CREATE TRIGGER IF NOT EXISTS platform_surface_observations_no_update BEFORE UPDATE ON platform_surface_observations BEGIN SELECT RAISE(ABORT,'platform_surface_observations is append-only'); END;CREATE TRIGGER IF NOT EXISTS platform_surface_observations_no_delete BEFORE DELETE ON platform_surface_observations BEGIN SELECT RAISE(ABORT,'platform_surface_observations is append-only'); END;CREATE TRIGGER IF NOT EXISTS platform_surface_contract_versions_no_update BEFORE UPDATE ON platform_surface_contract_versions BEGIN SELECT RAISE(ABORT,'platform_surface_contract_versions is append-only'); END;CREATE TRIGGER IF NOT EXISTS platform_surface_contract_versions_no_delete BEFORE DELETE ON platform_surface_contract_versions BEGIN SELECT RAISE(ABORT,'platform_surface_contract_versions is append-only'); END;CREATE TRIGGER IF NOT EXISTS platform_surface_replays_no_update BEFORE UPDATE ON platform_surface_replays BEGIN SELECT RAISE(ABORT,'platform_surface_replays is append-only'); END;CREATE TRIGGER IF NOT EXISTS platform_surface_replays_no_delete BEFORE DELETE ON platform_surface_replays BEGIN SELECT RAISE(ABORT,'platform_surface_replays is append-only'); END;`);}
  recordObservation(observation:SurfaceStepObservation):SurfaceStepObservation{const payload=JSON.stringify(observation),digest=hash(payload);const existing=this.db.prepare("SELECT observation_json,payload_hash FROM platform_surface_observations WHERE observation_id=?").get(observation.observationId) as {observation_json:string;payload_hash:string}|undefined;if(existing){if(existing.payload_hash!==digest||existing.observation_json!==payload)throw new PlatformSurfaceStoreConflict(`Observation ${observation.observationId} differs from stored value`);return JSON.parse(existing.observation_json) as SurfaceStepObservation;}this.db.prepare("INSERT INTO platform_surface_observations VALUES (?,?,?,?,?,?,?,?)").run(observation.observationId,observation.accountId,observation.platform,observation.format,observation.stepKey,payload,digest,iso(observation.observedAt));return observation;}
  listObservations(accountId:string,platform?:Platform,format?:PublicationFormat):readonly SurfaceStepObservation[]{const rows=this.db.prepare("SELECT observation_json FROM platform_surface_observations WHERE account_id=? ORDER BY observed_at,observation_id").all(accountId) as {observation_json:string}[];return rows.map(r=>JSON.parse(r.observation_json) as SurfaceStepObservation).filter(r=>(!platform||r.platform===platform)&&(!format||r.format===format));}
  recordContract(contract:PlatformSurfaceContract,now:string):StoredSurfaceContractVersion{const payload=JSON.stringify(contract),digest=hash(payload),versionId=`surface-version:${digest.slice(0,24)}`;const existing=this.db.prepare("SELECT contract_json,recorded_at FROM platform_surface_contract_versions WHERE version_id=?").get(versionId) as {contract_json:string;recorded_at:string}|undefined;if(existing)return{versionId,contract:JSON.parse(existing.contract_json) as PlatformSurfaceContract,recordedAt:existing.recorded_at};const recordedAt=iso(now);this.db.prepare("INSERT INTO platform_surface_contract_versions VALUES (?,?,?,?,?,?,?,?)").run(versionId,contract.contractId,contract.accountId,contract.postingProfileId,contract.status,payload,digest,recordedAt);return{versionId,contract,recordedAt};}
  latestContract(accountId:string,postingProfileId:string):StoredSurfaceContractVersion|null{const row=this.db.prepare("SELECT version_id,contract_json,recorded_at FROM platform_surface_contract_versions WHERE account_id=? AND posting_profile_id=? ORDER BY recorded_at DESC,rowid DESC LIMIT 1").get(accountId,postingProfileId) as {version_id:string;contract_json:string;recorded_at:string}|undefined;return row?{versionId:row.version_id,contract:JSON.parse(row.contract_json) as PlatformSurfaceContract,recordedAt:row.recorded_at}:null;}
  recordReplay(evidence:SurfaceReplayEvidence):SurfaceReplayEvidence{const payload=JSON.stringify(evidence),digest=hash(payload);const existing=this.db.prepare("SELECT evidence_json,payload_hash FROM platform_surface_replays WHERE replay_id=?").get(evidence.replayId) as {evidence_json:string;payload_hash:string}|undefined;if(existing){if(existing.payload_hash!==digest||existing.evidence_json!==payload)throw new PlatformSurfaceStoreConflict(`Replay ${evidence.replayId} differs from stored value`);return JSON.parse(existing.evidence_json) as SurfaceReplayEvidence;}this.db.prepare("INSERT INTO platform_surface_replays VALUES (?,?,?,?,?)").run(evidence.replayId,evidence.contractId,payload,digest,iso(evidence.checkedAt));return evidence;}
  listReplays(contractId:string):readonly SurfaceReplayEvidence[]{const rows=this.db.prepare("SELECT evidence_json FROM platform_surface_replays WHERE contract_id=? ORDER BY checked_at,replay_id").all(contractId) as {evidence_json:string}[];return rows.map(r=>JSON.parse(r.evidence_json) as SurfaceReplayEvidence);}
  close():void{this.db.close();}
}
