import { createHash } from "node:crypto";
import type { BrowserPageSessionPort } from "../../domain/browser-identity-ports.js";
import type { Platform, PublicationFormat } from "../../domain/model.js";
import type { CalibrationActionMode, SurfaceEnvironment, SurfaceLocatorCandidate, SurfaceStepObservation } from "../../domain/platform-surface.js";

interface RawCalibrationCapture { stepKey:string; mode:CalibrationActionMode; actionBlocked:boolean; url:string; tagName:string; id?:string; role?:string; ariaLabel?:string; text?:string; label?:string; name?:string; type?:string; testId?:string; }
function cssQuoted(value:string):string{return value.replaceAll("\\","\\\\").replaceAll('"','\\"');}
function uniqueCandidates(candidates:SurfaceLocatorCandidate[]):SurfaceLocatorCandidate[]{const seen=new Set<string>();return candidates.filter(item=>{const key=JSON.stringify(item.locator);if(seen.has(key))return false;seen.add(key);return true;});}
function locatorCandidates(raw:RawCalibrationCapture,allowGenericFileInput=false):SurfaceLocatorCandidate[]{
  const candidates:SurfaceLocatorCandidate[]=[],accessibleName=raw.ariaLabel||raw.label||raw.text;
  if(raw.role&&accessibleName)candidates.push({locator:{kind:"role",role:raw.role,value:accessibleName,exact:true},confidence:"HIGH",reason:"semantic role + accessible name"});
  if(raw.label)candidates.push({locator:{kind:"label",value:raw.label,exact:true},confidence:"HIGH",reason:"associated form label"});
  if(raw.testId)candidates.push({locator:{kind:"css",value:`[data-testid="${cssQuoted(raw.testId)}"]`},confidence:"HIGH",reason:"explicit data-testid"});
  if(raw.id)candidates.push({locator:{kind:"css",value:`[id="${cssQuoted(raw.id)}"]`},confidence:"HIGH",reason:"explicit element id"});
  if(raw.ariaLabel)candidates.push({locator:{kind:"css",value:`[aria-label="${cssQuoted(raw.ariaLabel)}"]`},confidence:"MEDIUM",reason:"aria-label attribute"});
  if(raw.name)candidates.push({locator:{kind:"css",value:`${raw.tagName}[name="${cssQuoted(raw.name)}"]`},confidence:"MEDIUM",reason:"element name attribute"});
  if(raw.text&&raw.text.length<=80)candidates.push({locator:{kind:"text",value:raw.text,exact:true},confidence:"LOW",reason:"visible text fallback"});
  if(allowGenericFileInput&&raw.tagName==="input"&&raw.type?.toLocaleLowerCase("en-US")==="file")candidates.push({locator:{kind:"css",value:'input[type="file"]'},confidence:"MEDIUM",reason:"unique enabled file input on current surface"});
  return uniqueCandidates(candidates);
}
function observationId(input:{accountId:string;stepKey:string;observedAt:string},candidates:readonly SurfaceLocatorCandidate[]):string{return`surface-observation:${createHash("sha256").update(`${input.accountId}|${input.stepKey}|${input.observedAt}|${JSON.stringify(candidates)}`).digest("hex").slice(0,24)}`;}

export class BrowserCalibrationRecorder {
  async environment(session:BrowserPageSessionPort):Promise<SurfaceEnvironment>{
    const raw=await session.evaluate<{userAgent:string;language:string;timeZone:string;width:number;height:number;scale:number}>(`(() => ({userAgent:navigator.userAgent,language:navigator.language||'und',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||'unknown',width:window.innerWidth,height:window.innerHeight,scale:window.devicePixelRatio||1}))()`);
    const major=Number(/(?:Chrome|Chromium)\/(\d+)/.exec(raw.userAgent)?.[1]??0);if(!major)throw new Error(`Unsupported/unknown Chromium user agent: ${raw.userAgent}`);const fingerprint=createHash("sha256").update(JSON.stringify([major,raw.language,raw.timeZone,raw.width,raw.height,raw.scale])).digest("hex");return{browserFamily:"chromium",browserMajor:major,language:raw.language,timeZone:raw.timeZone,viewportWidth:raw.width,viewportHeight:raw.height,deviceScaleFactor:raw.scale,fingerprint};
  }
  async arm(session:BrowserPageSessionPort,stepKey:string,mode:CalibrationActionMode):Promise<void>{
    const key=JSON.stringify(stepKey),actionMode=JSON.stringify(mode);await session.evaluate(`(() => {const stepKey=${key},mode=${actionMode};const w=window;if(w.__flerdvisionCalibrationCleanup)w.__flerdvisionCalibrationCleanup();w.__flerdvisionCalibrationCapture=null;let captured=false;const actionable=node=>{if(!(node instanceof Element))return null;return node.closest('button,[role],input,textarea,select,[contenteditable="true"],a[href],[data-testid]')||node;};const roleFor=el=>{const explicit=el.getAttribute('role');if(explicit)return explicit;const tag=el.tagName.toLowerCase(),type=(el.getAttribute('type')||'').toLowerCase();if(tag==='button'||(tag==='input'&&['button','submit','reset'].includes(type)))return'button';if(tag==='a'&&el.hasAttribute('href'))return'link';if(tag==='textarea'||(tag==='input'&&!['checkbox','radio','file','hidden'].includes(type)))return'textbox';if(tag==='select')return'combobox';if(tag==='input'&&type==='checkbox')return'checkbox';if(tag==='input'&&type==='radio')return'radio';return undefined;};const labelFor=el=>{if('labels'in el&&el.labels&&el.labels.length)return(el.labels[0].innerText||el.labels[0].textContent||'').trim().slice(0,160);const parent=el.closest('label');return parent?(parent.innerText||parent.textContent||'').trim().slice(0,160):undefined;};const record=(event,blocked)=>{if(captured)return;const el=actionable(event.target);if(!el)return;captured=true;w.__flerdvisionCalibrationCapture={stepKey,mode,actionBlocked:blocked,url:location.href,tagName:el.tagName.toLowerCase(),id:el.getAttribute('id')||undefined,role:roleFor(el),ariaLabel:el.getAttribute('aria-label')||undefined,text:(el.innerText||el.textContent||'').trim().replace(/\\s+/g,' ').slice(0,160)||undefined,label:labelFor(el),name:el.getAttribute('name')||undefined,type:el.getAttribute('type')||undefined,testId:el.getAttribute('data-testid')||undefined};};const stop=event=>{event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();record(event,true);};const observe=event=>record(event,false);const listeners=[];if(mode==='BLOCK_ACTION'){for(const type of['pointerdown','mousedown','click']){document.addEventListener(type,stop,true);listeners.push([type,stop]);}}else{document.addEventListener('click',observe,true);listeners.push(['click',observe]);}w.__flerdvisionCalibrationCleanup=()=>{for(const[type,fn]of listeners)document.removeEventListener(type,fn,true);w.__flerdvisionCalibrationCleanup=null;};return true;})()`);
  }
  async readObservation(session:BrowserPageSessionPort,input:{accountId:string;platform:Platform;format:PublicationFormat;stepKey:string;observedAt:string}):Promise<SurfaceStepObservation>{
    const raw=await session.evaluate<RawCalibrationCapture|null>(`window.__flerdvisionCalibrationCapture || null`);if(!raw||raw.stepKey!==input.stepKey)throw new Error(`No calibration capture available for ${input.stepKey}`);const environment=await this.environment(session),candidates=locatorCandidates(raw);if(candidates.length===0)throw new Error(`Captured ${input.stepKey} has no safe locator candidate; do not guess a CSS path`);return{observationId:observationId(input,candidates),accountId:input.accountId,platform:input.platform,format:input.format,stepKey:input.stepKey,observedAt:new Date(input.observedAt).toISOString(),environment,currentUrl:raw.url,tagName:raw.tagName,candidates,actionBlocked:raw.actionBlocked};
  }
  async readUniqueFileInputObservation(session:BrowserPageSessionPort,input:{accountId:string;platform:Platform;format:PublicationFormat;stepKey:string;observedAt:string}):Promise<SurfaceStepObservation>{
    const raw=await session.evaluate<RawCalibrationCapture[]>(`(() => {const inputs=Array.from(document.querySelectorAll('input[type="file"]')).filter(el=>!el.disabled);const labelFor=el=>{if(el.labels&&el.labels.length)return(el.labels[0].innerText||el.labels[0].textContent||'').trim().slice(0,160);const parent=el.closest('label');return parent?(parent.innerText||parent.textContent||'').trim().slice(0,160):undefined;};return inputs.map(el=>({stepKey:${JSON.stringify(input.stepKey)},mode:'OBSERVE_ACTION',actionBlocked:false,url:location.href,tagName:'input',id:el.getAttribute('id')||undefined,ariaLabel:el.getAttribute('aria-label')||undefined,label:labelFor(el),name:el.getAttribute('name')||undefined,type:'file',testId:el.getAttribute('data-testid')||undefined}));})()`);
    if(raw.length!==1)throw new Error(`Expected exactly one enabled file input for ${input.stepKey}; found ${raw.length}. Refusing ambiguous upload calibration.`);
    const environment=await this.environment(session),candidates=locatorCandidates(raw[0]!,true);if(candidates.length===0)throw new Error(`Unique file input for ${input.stepKey} has no safe locator candidate`);return{observationId:observationId(input,candidates),accountId:input.accountId,platform:input.platform,format:input.format,stepKey:input.stepKey,observedAt:new Date(input.observedAt).toISOString(),environment,currentUrl:raw[0]!.url,tagName:"input",candidates,actionBlocked:false};
  }
  async clear(session:BrowserPageSessionPort):Promise<void>{await session.evaluate(`(() => {if(window.__flerdvisionCalibrationCleanup)window.__flerdvisionCalibrationCleanup();window.__flerdvisionCalibrationCapture=null;return true;})()`);}
}
