import { createHash } from "node:crypto";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { FixedTestRunnerPort, WorkspaceRegistryPort } from "../../domain/workspace-ports.js";
import type { OperatorBrowserSession } from "../../application/browser-bootstrap.js";
import { WorkspaceService, workspaceRuntimeLayout } from "../../application/workspaces.js";
import { TestLabService, SELF_SERVICE_TEST_CATALOG } from "../../application/test-lab.js";
import { SqliteControlPlaneStore } from "../storage/sqlite.js";
import { BrowserProfileDirectoryResolver, DurableBrowserProfileLockAdapter, FileBrowserProfileLockAdapter } from "../browser/profile-lock.js";
import { ChromiumCdpRuntimeAdapter } from "../browser/chromium-cdp.js";
import { BrowserBootstrapService } from "../../application/browser-bootstrap.js";
import type { Platform } from "../../domain/model.js";

interface DriveSetup { rootFolderId: string; configuredAt: string; }
interface TestResultRecord { testId: string; passed: boolean; summary: string; checkedAt: string; artifactRefs: readonly string[]; }
interface RetainedOperatorSession { session: OperatorBrowserSession; store: SqliteControlPlaneStore; }

function escapeHtml(value: string): string { return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function parseBasicAuth(header: string | string[] | undefined): {username:string;password:string}|null { if(typeof header!=="string"||!header.startsWith("Basic "))return null; try{const decoded=Buffer.from(header.slice(6),"base64").toString("utf8"); const i=decoded.indexOf(":"); return i<0?null:{username:decoded.slice(0,i),password:decoded.slice(i+1)};}catch{return null;} }
async function readForm(req: IncomingMessage): Promise<URLSearchParams> { return await new Promise((resolvePromise)=>{let body="";req.on("data",c=>{body+=c.toString();});req.on("end",()=>resolvePromise(new URLSearchParams(body)));}); }
function platform(value: string): Platform { if(value==="instagram"||value==="tiktok"||value==="youtube") return value; throw new Error(`Unsupported platform: ${value}`); }
function bootstrapUrl(platformName: Platform): string { return platformName === "instagram" ? "https://www.instagram.com/" : platformName === "tiktok" ? "https://www.tiktok.com/" : "https://studio.youtube.com/"; }

export interface SelfServiceHttpOptions {
  runtimeRoot: string;
  repoRoot: string;
  password: string;
  username?: string;
  host?: string;
  port?: number;
  chromiumExecutablePath: string;
  testRunner: FixedTestRunnerPort;
}

export class SelfServiceHttpServer {
  private server: Server | undefined;
  private readonly csrf = createHash("sha256").update(`${Date.now()}|${Math.random()}`).digest("hex");
  private readonly sessions = new Map<string, RetainedOperatorSession>();
  constructor(private readonly registry: WorkspaceRegistryPort, private readonly options: SelfServiceHttpOptions) { if(!options.password) throw new Error("Self-service UI password is required"); }
  private authorized(req: IncomingMessage): boolean { const auth=parseBasicAuth(req.headers.authorization); return Boolean(auth&&auth.username===(this.options.username??"flerdvision")&&auth.password===this.options.password); }
  private deny(res: ServerResponse): void { res.statusCode=401;res.setHeader("WWW-Authenticate",'Basic realm="Flerdvision Setup"');res.end("Authentication required"); }
  private redirect(res: ServerResponse, location:string): void { res.statusCode=303;res.setHeader("Location",location);res.end(); }
  private drivePath(workspaceId:string): string { return resolve(workspaceRuntimeLayout(this.options.runtimeRoot,workspaceId).configDir,"drive.json"); }
  private testsPath(workspaceId:string): string { return resolve(workspaceRuntimeLayout(this.options.runtimeRoot,workspaceId).configDir,"test-results.json"); }
  private readDrive(workspaceId:string): DriveSetup|null { const p=this.drivePath(workspaceId); return existsSync(p)?JSON.parse(readFileSync(p,"utf8")) as DriveSetup:null; }
  private readTests(workspaceId:string): TestResultRecord[] { const p=this.testsPath(workspaceId); return existsSync(p)?JSON.parse(readFileSync(p,"utf8")) as TestResultRecord[]:[]; }
  private recordTest(workspaceId:string,result:TestResultRecord):void { const all=this.readTests(workspaceId).filter(x=>x.testId!==result.testId); all.push(result); writeFileSync(this.testsPath(workspaceId),JSON.stringify(all,null,2),{encoding:"utf8",mode:0o600}); }
  private shell(title:string, body:string):string { return `<!doctype html><html><head><meta charset=utf-8><title>${escapeHtml(title)}</title><style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:30px auto;padding:0 20px}a{color:inherit}.card{border:1px solid #ddd;border-radius:10px;padding:16px;margin:12px 0}.ok{color:#087f23}.warn{color:#9a6700}.bad{color:#b42318}input,select,button{padding:7px;margin:3px}code,pre{background:#f5f5f5;padding:3px 5px;border-radius:4px}pre{white-space:pre-wrap}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ddd;padding:7px;text-align:left}</style></head><body>${body}</body></html>`; }
  private home():string { const rows=this.registry.list().map(w=>`<tr><td><a href="/workspaces/${encodeURIComponent(w.workspaceId)}">${escapeHtml(w.displayName)}</a></td><td>${escapeHtml(w.workspaceId)}</td><td>${escapeHtml(w.status)}</td><td>${escapeHtml(w.timezone)}</td></tr>`).join(""); return this.shell("Flerdvision Setup",`<h1>Flerdvision Self-Service</h1><p>Workspaces are isolated by database, browser profiles and evidence storage.</p><table><tr><th>Name</th><th>ID</th><th>Status</th><th>Timezone</th></tr>${rows||"<tr><td colspan=4>No workspaces yet</td></tr>"}</table><div class=card><h2>Create workspace</h2><form method=post action=/workspaces><input type=hidden name=csrf value=${this.csrf}><input name=workspaceId placeholder="workspace id" required><input name=displayName placeholder="display name" required><input name=timezone value="Europe/Vienna" required><button>Create</button></form></div>`); }
  private workspacePage(workspaceId:string):string {
    const workspace=this.registry.get(workspaceId); if(!workspace) return this.shell("Not found","<h1>Workspace not found</h1>");
    const layout=workspaceRuntimeLayout(this.options.runtimeRoot,workspaceId); const drive=this.readDrive(workspaceId); const tests=this.readTests(workspaceId); const store=new SqliteControlPlaneStore(layout.databasePath);
    let accounts; try { accounts=store.listSocialAccounts().map(a=>({account:a,identity:store.listBrowserIdentities().find(i=>i.identity.accountId===a.account.accountId)})); } finally { store.close(); }
    const accountRows=accounts.map(({account,identity})=>`<tr><td>${escapeHtml(account.account.platform)}</td><td>@${escapeHtml(account.account.expectedHandle)}</td><td>${identity?escapeHtml(identity.identity.identityId):"missing"}</td><td>${identity&&this.sessions.has(`${workspaceId}:${identity.identity.identityId}`)?"browser open":"closed"}</td><td>${identity?`<form method=post action="/workspaces/${workspaceId}/browser/${encodeURIComponent(identity.identity.identityId)}/open"><input type=hidden name=csrf value=${this.csrf}><button>Open login browser</button></form><form method=post action="/workspaces/${workspaceId}/browser/${encodeURIComponent(identity.identity.identityId)}/close"><input type=hidden name=csrf value=${this.csrf}><button>Close browser</button></form>`:""}</td></tr>`).join("");
    const testRows=SELF_SERVICE_TEST_CATALOG.map(t=>{const r=tests.find(x=>x.testId===t.testId);return `<tr><td>${escapeHtml(t.label)}</td><td>${escapeHtml(t.risk)}</td><td class=${r?.passed?"ok":r?"bad":"warn"}>${r?r.passed?"PASS":"FAIL":"NOT RUN"}</td><td><form method=post action="/workspaces/${workspaceId}/tests/${encodeURIComponent(t.testId)}"><input type=hidden name=csrf value=${this.csrf}><button>Run</button></form>${r?`<details><summary>details</summary><pre>${escapeHtml(r.summary)}</pre></details>`:""}</td></tr>`}).join("");
    return this.shell(workspace.displayName,`<p><a href=/>&larr; Workspaces</a></p><h1>${escapeHtml(workspace.displayName)}</h1><p><strong>${escapeHtml(workspace.workspaceId)}</strong> · ${escapeHtml(workspace.status)} · ${escapeHtml(workspace.timezone)}</p><div class=card><h2>1 · Google Drive</h2><p class=${drive?"ok":"warn"}>${drive?`Configured root: ${escapeHtml(drive.rootFolderId)}`:"Not configured"}</p><form method=post action="/workspaces/${workspaceId}/drive"><input type=hidden name=csrf value=${this.csrf}><input name=rootFolderId placeholder="Drive root folder ID" value="${escapeHtml(drive?.rootFolderId??"")}" required><button>Save mapping</button></form><small>No Drive credential is stored here; credentials stay in deployment secrets.</small></div><div class=card><h2>2 · Social accounts</h2><table><tr><th>Platform</th><th>Expected account</th><th>Browser identity</th><th>Session</th><th>Action</th></tr>${accountRows||"<tr><td colspan=5>No accounts registered</td></tr>"}</table><form method=post action="/workspaces/${workspaceId}/accounts"><input type=hidden name=csrf value=${this.csrf}><select name=platform><option>instagram</option><option>tiktok</option><option>youtube</option></select><input name=accountId placeholder="account id" required><input name=expectedHandle placeholder="expected handle" required><input name=creatorId placeholder="creator id (optional)"><button>Register isolated account</button></form><small>Passwords and 2FA are never stored in Flerdvision config. Login happens in the isolated browser profile.</small></div><div class=card><h2>3 · Test Lab</h2><table><tr><th>Test</th><th>Risk</th><th>Status</th><th>Action</th></tr>${testRows}</table></div><div class=card><h2>Workspace isolation</h2><pre>${escapeHtml(JSON.stringify(layout,null,2))}</pre></div>`);
  }
  private async handle(req:IncomingMessage,res:ServerResponse):Promise<void>{ if(!this.authorized(req)){this.deny(res);return;} const method=req.method??"GET"; const path=(req.url??"/").split("?",1)[0]??"/";
    if(method==="GET"&&path==="/"){res.statusCode=200;res.setHeader("Content-Type","text/html; charset=utf-8");res.end(this.home());return;}
    const wm=path.match(/^\/workspaces\/([^/]+)$/); if(method==="GET"&&wm){res.statusCode=200;res.setHeader("Content-Type","text/html; charset=utf-8");res.end(this.workspacePage(decodeURIComponent(wm[1]!)));return;}
    if(method!=="POST"){res.statusCode=404;res.end("Not found");return;} const form=await readForm(req); if(form.get("csrf")!==this.csrf){res.statusCode=403;res.end("Invalid CSRF token");return;}
    try{
      if(path==="/workspaces"){const ws=new WorkspaceService(this.registry,this.options.runtimeRoot).create({workspaceId:form.get("workspaceId")??"",displayName:form.get("displayName")??"",timezone:form.get("timezone")??"Europe/Vienna",now:new Date().toISOString()});this.redirect(res,`/workspaces/${ws.workspace.workspaceId}`);return;}
      const drive=path.match(/^\/workspaces\/([^/]+)\/drive$/); if(drive){const id=decodeURIComponent(drive[1]!); const rootFolderId=(form.get("rootFolderId")??"").trim(); if(!rootFolderId) throw new Error("Drive root folder ID is required"); writeFileSync(this.drivePath(id),JSON.stringify({rootFolderId,configuredAt:new Date().toISOString()},null,2),{encoding:"utf8",mode:0o600}); this.redirect(res,`/workspaces/${id}`);return;}
      const accounts=path.match(/^\/workspaces\/([^/]+)\/accounts$/); if(accounts){const id=decodeURIComponent(accounts[1]!); const layout=workspaceRuntimeLayout(this.options.runtimeRoot,id); const store=new SqliteControlPlaneStore(layout.databasePath); try{const p=platform(form.get("platform")??"");const accountId=(form.get("accountId")??"").trim();const expectedHandle=(form.get("expectedHandle")??"").trim();const creatorId=(form.get("creatorId")??"").trim(); const now=new Date().toISOString(); const actor={type:"operator" as const,id:this.options.username??"flerdvision"};store.registerSocialAccount({accountId,platform:p,expectedHandle,enabled:true,...(creatorId?{creatorId}: {})},now,actor);store.registerBrowserIdentity({identityId:`browser_${accountId}`,accountId,platform:p,profileKey:`${p}/${accountId}`,expectedHandle,enabled:true},now,actor);}finally{store.close();}this.redirect(res,`/workspaces/${id}`);return;}
      const test=path.match(/^\/workspaces\/([^/]+)\/tests\/([^/]+)$/); if(test){const id=decodeURIComponent(test[1]!);const testId=decodeURIComponent(test[2]!);const result=await new TestLabService(this.options.testRunner,this.options.repoRoot).run(testId);this.recordTest(id,{testId,...result,checkedAt:new Date().toISOString()});this.redirect(res,`/workspaces/${id}`);return;}
      const open=path.match(/^\/workspaces\/([^/]+)\/browser\/([^/]+)\/open$/); if(open){const id=decodeURIComponent(open[1]!);const identityId=decodeURIComponent(open[2]!);const key=`${id}:${identityId}`;if(this.sessions.has(key))throw new Error("Browser session already open");const layout=workspaceRuntimeLayout(this.options.runtimeRoot,id);const store=new SqliteControlPlaneStore(layout.databasePath);const identity=store.getBrowserIdentity(identityId);if(!identity){store.close();throw new Error(`Unknown browser identity: ${identityId}`);}const resolver=new BrowserProfileDirectoryResolver(layout.profilesDir);const locks=new DurableBrowserProfileLockAdapter(store,new FileBrowserProfileLockAdapter(resolver));const runtime=new ChromiumCdpRuntimeAdapter({profilesRoot:layout.profilesDir,executablePath:this.options.chromiumExecutablePath});const session=await new BrowserBootstrapService(store,runtime,locks).openForOperator({identityId,ownerId:this.options.username??"flerdvision",bootstrapUrl:bootstrapUrl(identity.identity.platform),now:new Date().toISOString(),headless:false});this.sessions.set(key,{session,store});this.redirect(res,`/workspaces/${id}`);return;}
      const close=path.match(/^\/workspaces\/([^/]+)\/browser\/([^/]+)\/close$/); if(close){const id=decodeURIComponent(close[1]!);const identityId=decodeURIComponent(close[2]!);const key=`${id}:${identityId}`;const retained=this.sessions.get(key);if(retained){this.sessions.delete(key);try{await retained.session.close();}finally{retained.store.close();}}this.redirect(res,`/workspaces/${id}`);return;}
      res.statusCode=404;res.end("Not found");
    }catch(error){res.statusCode=409;res.setHeader("Content-Type","text/plain; charset=utf-8");res.end(error instanceof Error?error.message:String(error));}
  }
  async start():Promise<{host:string;port:number}>{if(this.server)throw new Error("Self-service server already started");const host=this.options.host??"127.0.0.1";const port=this.options.port??0;this.server=createServer((req,res)=>{void this.handle(req,res);});await new Promise<void>(resolvePromise=>this.server!.listen(port,host,resolvePromise));const a=this.server.address();if(!a||typeof a==="string")throw new Error("Self-service server did not expose address");return{host,port:a.port};}
  async stop():Promise<void>{for(const [key,retained] of this.sessions){this.sessions.delete(key);try{await retained.session.close();}finally{retained.store.close();}}if(!this.server)return;const s=this.server;this.server=undefined;await new Promise<void>((resolvePromise,reject)=>s.close(error=>error?reject(error):resolvePromise()));}
}
