import { createHash } from "node:crypto";
import type { PostingProfile } from "../domain/distribution.js";
import type { UiLocator } from "../domain/platform-ui.js";
import type { PlatformSurfaceContract, SurfaceLocatorCandidate, SurfaceReplayEvidence, SurfaceStepObservation } from "../domain/platform-surface.js";
import { surfaceRecipeForPostingProfile } from "../domain/platform-surface.js";

function locatorKey(locator:UiLocator):string{return JSON.stringify([locator.kind,locator.role??"",locator.value,locator.exact??false]);}
function rank(candidate:SurfaceLocatorCandidate):number{const confidence=candidate.confidence==="HIGH"?0:candidate.confidence==="MEDIUM"?10:20;const kind=candidate.locator.kind==="role"?0:candidate.locator.kind==="label"?1:candidate.locator.kind==="css"?2:3;return confidence+kind;}

export function buildRecordedSurfaceContract(input:{accountId:string;profile:PostingProfile;observations:readonly SurfaceStepObservation[];createdAt:string;}):PlatformSurfaceContract{
  const recipe=surfaceRecipeForPostingProfile(input.profile),matching=input.observations.filter(item=>item.accountId===input.accountId&&item.platform===recipe.platform&&item.format===recipe.format).sort((a,b)=>a.observedAt.localeCompare(b.observedAt));
  if(matching.length===0)throw new Error("No calibration observations for this account/profile");
  // Observations are append-only. Recalibration must use one coherent, latest browser/locale/viewport cohort rather than mixing historical environments forever.
  const latestEnvironmentFingerprint=matching.at(-1)!.environment.fingerprint,relevant=matching.filter(item=>item.environment.fingerprint===latestEnvironmentFingerprint),environment=relevant[0]!.environment;
  const steps=recipe.steps.map(definition=>{const observations=relevant.filter(item=>item.stepKey===definition.stepKey);if(definition.required&&observations.length===0)throw new Error(`Missing calibration observation for ${definition.stepKey} in latest environment ${latestEnvironmentFingerprint}`);if(definition.actionMode==="BLOCK_ACTION"&&observations.some(item=>!item.actionBlocked))throw new Error(`${definition.stepKey} must be captured with action blocking`);const frequencies=new Map<string,{candidate:SurfaceLocatorCandidate;count:number}>();for(const observation of observations)for(const candidate of observation.candidates){const key=locatorKey(candidate.locator),current=frequencies.get(key);frequencies.set(key,{candidate,count:(current?.count??0)+1});}const common=[...frequencies.values()].filter(item=>item.count===observations.length).sort((a,b)=>rank(a.candidate)-rank(b.candidate));if(observations.length>0&&common.length===0)throw new Error(`No stable locator survived all observations for ${definition.stepKey}`);const primary=common[0]?.candidate.locator;if(!primary)throw new Error(`No locator available for ${definition.stepKey}`);return{stepKey:definition.stepKey,label:definition.label,actionMode:definition.actionMode,locator:primary,fallbackLocators:common.slice(1,4).map(item=>item.candidate.locator),observations:observations.length};});
  const contractId=`surface:${createHash("sha256").update(`${input.accountId}|${input.profile.postingProfileId}|${environment.fingerprint}|${steps.map(item=>locatorKey(item.locator)).join("|")}`).digest("hex").slice(0,24)}`;
  return{contractId,accountId:input.accountId,platform:recipe.platform,format:recipe.format,postingProfileId:input.profile.postingProfileId,environment,steps,status:"RECORDED",createdAt:new Date(input.createdAt).toISOString()};
}

export function qualifySurfaceContract(contract:PlatformSurfaceContract,evidence:readonly SurfaceReplayEvidence[],calibratedAt:string):PlatformSurfaceContract{
  const relevant=evidence.filter(item=>item.contractId===contract.contractId).sort((a,b)=>a.checkedAt.localeCompare(b.checkedAt)),lastThree=relevant.slice(-3);if(lastThree.length<3)throw new Error("Surface contract requires three successful prepare-only replays");if(lastThree.some(item=>!item.passed||!item.reachedFinalActionBoundary))throw new Error("Latest three surface replays must pass and reach the final-action boundary");if(lastThree.some(item=>item.finalActionInvoked))throw new Error("Surface calibration replay must never invoke final publish action");if(lastThree.some(item=>item.environmentFingerprint!==contract.environment.fingerprint))throw new Error("Surface replay environment differs from the recorded contract");return{...contract,status:"CALIBRATED",calibratedAt:new Date(calibratedAt).toISOString()};
}
